title: Charlie Lu
author:
  name: Charlie Lu
  email: charlielu05@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Data Science blog, documenting my Data Science/Machine Learning/Software Engineering journey.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-include-cache

markdown: kramdown
kramdown:
   math_engine: katex

